name: is-up-to-date
on:
 schedule:
  - cron: '0 8 * * *'

jobs:
    build:
      name: Update
      runs-on: ubuntu-latest
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v1
        - name: Update
          run: ./update.ps1
          shell: pwsh

