name: Test
on: [workflow_dispatch]

jobs:
    build:
      name: Update
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Update
          run: ./update.ps1
          shell: pwsh
