name: Test
on: 
 workflow_dispatch:

jobs:
    build:
      name: Update
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Update
          run: ./update.ps1
          shell: pwsh
